const character_stats={
    s_0_0://soldier, age:0, variation:0
    {
        name:'s_0_0',
        rngd:false,
        hp:30,
        dmg:5,
        hit_t:1000, //time between each hit of the animation
        attack_start_t:300, //the time it takes to start the animation (only fires 1 time per engagement startup)
        speed:3 //normalde 10da sabit duruyor, 1000 pixeli 10 saniyede gidiyor, ama hızı 5 yaparsan 20 saniyede gider.
    },
    s_1_0:
    {
        name:'s_1_0',
        rngd:false,
        hp:200,
        dmg:20,
        hit_t:200,
        attack_start_t:200,
        speed:3
    },
    s_2_0:
    {
        name:'s_2_0',
        rngd:false,
        hp:400,
        dmg:40,
        hit_t:200,
        attack_start_t:200,
        speed:3
    },
    s_3_0:
    {
        name:'s_3_0',
        rngd:false,
        hp:800,
        dmg:80,
        hit_t:200,
        attack_start_t:200,
        speed:3
    },
    s_4_0:
    {
        name:'s_4_0',
        rngd:false,
        hp:2000,
        dmg:200,
        hit_t:200,
        attack_start_t:200,
        speed:7
    },

    a_0_0:
    {
        name:'a_0_0',
        rngd:true,
        hp:20,
        dmg:3,
        dmg_rngd:1,
        hit_t:700, 
        attack_start_t:300,
        hit_t_rngd:1500, 
        attack_start_t_rngd:700,
        attack_range:200,
        speed:5
    },
    a_1_0:
    {
        name:'a_1_0',
        rngd:true,
        hp:20,
        dmg:7,
        dmg_rngd:1,
        hit_t:1000, 
        attack_start_t:300,
        hit_t_rngd:1000, 
        attack_start_t_rngd:300,
        attack_range:300, 
        speed:3
    },
    a_2_0:
    {
        name:'a_2_0',
        rngd:true,
        hp:20,
        dmg:7,
        dmg_rngd:1,
        hit_t:1000, 
        attack_start_t:300,
        hit_t_rngd:1000, 
        attack_start_t_rngd:300,
        attack_range:300, 
        speed:3
    },
    a_3_0:
    {
        name:'a_3_0',
        rngd:true,
        hp:20,
        dmg:7,
        dmg_rngd:1,
        hit_t:1000, 
        attack_start_t:300,
        hit_t_rngd:1000, 
        attack_start_t_rngd:300,
        attack_range:300, 
        speed:3
    },
    a_4_0:
    {
        name:'a_4_0',
        rngd:true,
        hp:20,
        dmg:7,
        dmg_rngd:1,
        hit_t:1000, 
        attack_start_t:300,
        hit_t_rngd:1000, 
        attack_start_t_rngd:300,
        attack_range:300, 
        speed:3
    }
}